---
# Volume for Storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bankdb-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /mountdata/bankdb
---
# Request Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bankdb-pvc
  namespace: webapps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankdb
spec:
  selector:
    matchLabels:
      app: bankdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bankdb
    spec:
      containers:
      - image: mysql:8
        name: bankdb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Suresh@1997"
        - name: MYSQL_DATABASE
          value: "bankappdb"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: bankdb-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: bankdb-storage
        persistentVolumeClaim:
          claimName: bankdb-pvc
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: bankdb-service
spec:
  ports:
  - port: 3306
  selector:
    app: bankdb
---
# Java Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp
        image: nagasuribabukola/bankapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://bankdb-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: "Suresh@1997"
---
# Bank Application Service
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bankapp